#!/usr/bin/with-contenv bash

# Directories.
mkdir -p /factorio
mkdir -p $SAVES
mkdir -p $CONFIG
mkdir -p $MODS
mkdir -p $SCENARIOS
mkdir -p $SCRIPTOUTPUT

# Permissions.
chown -R abc:abc \
    /opt/factorio \
    /factorio

chmod g+w $SAVES
chmod g+w $CONFIG
chmod g+w $MODS
chmod g+w $SCENARIOS
chmod g+w $SCRIPTOUTPUT
